### ISSUE TITLE
Is there a test project where the examples are working?

### ISSUE THREAD

**Issue by Transigent** [lppkarl/Trady#35]
Hi I am very intersted in experimenting with this project, but I have not had any luck with the sample snippets on https://github.com/lppkarl/Trady

I imported using Nuget and made a basic test harness:

```
Dim closes = New List(Of Candle)
Dim closes2 = New List(Of Candle)

        Using Context As New mainEntities
            Dim Results = (From HR In Context.HistoricalRecords
                           Where HR.instrument_id = 247
                           Order By HR.time Ascending).ToList

            Dim ResultCount As Integer = 0
            For Each HR In Results
                ResultCount += 1
                Dim NewCandle As Candle = New Candle(TimeFunctions.ConvertUTCToDate(HR.time), HR.open, HR.high, HR.low, HR.close, HR.volume_to)
                If ResultCount < 150 Then
                    closes.Add(NewCandle)
                Else
                    closes2.Add(NewCandle)
                End If
            Next
        End Using
```

Then I tried the sample:

```
Dim smaTs = closes.Sma(30)
Dim sma = closes.Sma(30)(40)

        Dim buyRule = Rule.Create(Function(c) c.IsFullStoBullishCross(14, 3, 3)).[And](Function(c) c.IsMacdOscBullish(12, 26, 9)).[And](Function(c) c.IsSmaOscBullish(10, 30)).[And](Function(c) c.IsAccumDistBullish())

        Dim sellRule = Rule.Create(Function(c) c.IsFullStoBearishCross(14, 3, 3)).[Or](Function(c) c.IsMacdBearishCross(12, 24, 9)).[Or](Function(c) c.IsSmaBearishCross(10, 30))
        Dim runner = New Backtest.Builder().Add(closes, 10).Add(closes2, 30).Buy(buyRule).Sell(sellRule).Build()
        Dim result = runner.Run(200, 1)

        Console.WriteLine(String.Format("Transaction count: {0:#.##}, P/L ratio: {1:0.##}%, Principal: {2:#}, Total: {3:#}",
                                        result.TotalCorrectedTransactionCount,
                                        result.TotalCorrectedProfitLossRatio * 100,
                                        result.TotalPrincipal,
                                        result.TotalCorrectedBalance))

```

--------------------

On the line:
`Dim result = runner.Run(200, 1)`
I get 

> Object reference not set to an instance of an object.

This happens for both Run and RunAsync.

So instead I tried:

```
     Dim buyRule = Rule.Create(Function(c) c.IsEma10BullishCrossEma30()).[And](Function(c) c.IsEma10Rising())

        Dim sellRule = Rule.Create(Function(c) c.IsEma10BearishCrossEma30()).[Or](Function(c) c.IsEma10Dropping())

        Dim runner = New Backtest.Builder().Add(closes, 10).Buy(buyRule).Sell(sellRule).Build()

        Dim result = Await runner.RunAsync(10000, 1)
```

---------------

Now on the line:
`Dim result = Await runner.RunAsync(10000, 1)`
I get 

> Method not found: 'System.ValueTuple`3<!3,!3,!3> Trady.Analysis.Infrastructure.AnalyzableBase`4.ComputeNeighbour(Int32)'.

----------------

I appreciate the effort you have put into this but I am having no luck with the samples indicated. If there was a simple project where calls like this are succeeding, that might help us work out our problems.

There also seems to be a shortage of comments in the code or other documentation explaining how to use it successfully, so I am not clear where to go from here.

Thanks for any help.

**Comment by lppkarl** [comment]
Hi. The most updated version is v3.1. Some of your problem should be fixed in this version. Please pull the branch and try to see if the problem is fixed.

**Comment by Transigent** [comment]
Thanks but I got 3.1 and the the same thing happens. 
First error :  'Object reference not set to an instance of an object.'

in Runner.cs

```
private void SellAsset(IIndexedOhlcv indexedCandle, decimal premium, IDictionary<IEnumerable<IOhlcv>, decimal> assetCashMap, IList<Transaction> transactions)
        {
            if (assetCashMap.TryGetValue(indexedCandle.BackingList, out _))
            {
                var nextIOhlcvData = indexedCandle.Next;
                var lastTransaction = transactions.LastOrDefault(t => t.IOhlcvDatas.Equals(indexedCandle.BackingList));

                decimal cashIn = nextIOhlcvData.Open * lastTransaction.Quantity - premium;
                decimal plRatio = (cashIn - lastTransaction.AbsoluteCashFlow) / lastTransaction.AbsoluteCashFlow;
                assetCashMap[indexedCandle.BackingList] += cashIn;

                transactions.Add(new Transaction(indexedCandle.BackingList, nextIOhlcvData.Index, nextIOhlcvData.DateTime, TransactionType.Sell, lastTransaction.Quantity, cashIn));
                OnSold?.Invoke(indexedCandle.BackingList, nextIOhlcvData.Index, nextIOhlcvData.DateTime, nextIOhlcvData.Open, lastTransaction.Quantity, cashIn, assetCashMap[indexedCandle.BackingList], plRatio);
            }
        }
```

Error is thrown on the line 

`decimal cashIn = nextIOhlcvData.Open * lastTransaction.Quantity - premium;`

------

In the second sample above, I am getting new errors:

'IsEma10BullishCrossEma30' is not a member of 'IIndexedOhlcv'
'IsEma10Rising' is not a member of 'IIndexedOhlcv'.	
'IsEma10BearishCrossEma30' is not a member of 'IIndexedOhlcv'
'IsEma10Dropping' is not a member of 'IIndexedOhlcv'



Thanks

**Comment by Transigent** [comment]
Again if there were a simple project where these samples were working, we could use that to solve our own problems.

**Comment by irperez** [comment]
@Transigent I don't see those 4 methods anywhere in the project. 

IsEma10BullishCrossEma30
IsEma10Rising
IsEma10BearishCrossEma30
IsEma10Dropping

Can you confirm once again you were working on v3.1?  Are these custom indicators or methods you created for this library?

I got your first example working fine in a unit test.

**Comment by irperez** [comment]
@Transigent I just noticed that those four methods were an example that IppKarl created for the README file. But they are not actual methods in the library.  FYI.  Hope that answers your question.

**Comment by lppkarl** [comment]
The issue is no longer active, closed.
